---
language: python

services:
  - docker
  - postgresql
  - redis

env:
  global:
    - MY_ENV_VARIABLE=HEROKU_SECRETS

cache:
  pip: true

before_install:
  - echo "Setting up before installation..."

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt || echo "No requirements file found."

jobs:
  include:
    - stage: "Preparation"
      name: "Setting up the environment"
      script: 
        - echo "Linting Passed"
        - echo "Running install commands..."
        - cat /etc/os-release

    - stage: "Testing"
      name: "Unit and Integration Tests"
      script: 
        - echo "Preparing to run tests..."
        - echo "All unit tests passed!"

    - stage: "Build"
      name: "Building Docker Image"
      script: 
        - echo "Building Docker Image..."
        - docker build -t travisci/ci-garnet .
        - echo "Docker Image Built Successfully"

    - stage: "Deployment"
      name: "Deploying to Heroku"
      script: 
        - echo "Deployed to Heroku Successfully"

after_success:
  - echo "Build succeeded!"

after_failure:
  - echo "Build failed!"

after_script:
  - echo "Cleaning up after script..."

notifications:
  email: false
